services:
  web:
    build: backend/
    container_name: backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - nasa_db:/code/data/
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
    env_file:
      - backend/.env

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

volumes:
  nasa_db:
